name: golangci-lint
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  audit:
    name: Run linter and tests
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - uses: actions/setup-go@v5
        with:
          go-version: 1.23
          
      - name: Verify deps
        run: go mod verify
        
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1
          
      - name: Run unit tests
        run: go test ./...

  package:
    name: Build and push docker image
    needs: audit
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v6
        with:
          context: .
          file: scripts/build/package/Dockerfile
          push: false

  aboba:
    name: Run Aboba
    runs-on: self-hosted
    steps:
      - run: |
        echo Hello!
      
