name: Audit, Build, Push
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  audit:
    name: Run linter and tests
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      # https://github.com/actions/setup-go/issues/424
      - uses: actions/setup-go@v5
        with:
          go-version: 1.23.3
          
      - name: Setup Golang caches
        uses: actions/cache@v4
        with:
         path: |
          ~/.cache/go-build
          ~/go/pkg/mod
         key: ${{ runner.os }}-golang-${{ hashFiles('**/go.sum') }}
         restore-keys: |
           ${{ runner.os }}-golang-
          
      - name: Verify deps
        run: go mod verify
        
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1
          
      - name: Run unit tests
        run: go test ./...

  package:
    name: Build and push docker image
    needs: audit
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # https://github.com/docker/build-push-action/issues/44
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-config-inline: |
            [registry."${{ vars.CONTAINER_REGISTRY }}"]
              http = true
      
      - name: Collect image tag
        run: echo "tag=$REGISTRY/$REPOSITORY:$BRANCH_NAME" >> $GITHUB_OUTPUT
        id: collect_image_tag
        env: 
          REGISTRY: ${{ vars.CONTAINER_REGISTRY }}
          REPOSITORY: ${{ github.repository }}
          BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: ${{ runner.temp }}/buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
       
      - uses: docker/build-push-action@v6
        with:
          context: .      
          push: true
          file: scripts/build/package/Dockerfile
          tags: ${{ steps.collect_image_tag.outputs.tag }}
          build-args: |
            GOPROXY=${{ vars.GOPROXY_URL }}

          cache-from: type=local,src=${{ runner.temp }}/.buildx-cache
          cache-to: type=local,dest=${{ runner.temp }}/.buildx-cache-new,mode=max


      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: |
          rm -rf ${{ runner.temp }}/.buildx-cache
          mv ${{ runner.temp }}/.buildx-cache-new ${{ runner.temp }}/.buildx-cache
