name: Audit, Build, Push
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  audit:
    name: Run linter and tests
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - uses: actions/setup-go@v5
        with:
          go-version: 1.23
          
      - name: Setup Golang caches
        uses: actions/cache@v4
        with:
         path: |
          ~/.cache/go-build
          ~/go/pkg/mod
         key: ${{ runner.os }}-golang-${{ hashFiles('**/go.sum') }}
         restore-keys: |
           ${{ runner.os }}-golang-
          
      - name: Verify deps
        run: go mod verify
        
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1
          
      - name: Run unit tests
        run: go test ./...

  package:
    name: Build and push docker image
    needs: audit
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # https://github.com/docker/build-push-action/issues/44
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          config-inline: |
            [registry."{{ vars.CONTAINER_REGISTRY }}"]
              http = true
              insecure = true
      
      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: |
            ${{ vars.CONTAINER_REGISTRY }}/${{ github.repository }}

      - name: Check for metadata
        env:
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
        run: |
          echo $tags
        
      - uses: docker/build-push-action@v6
        with:
          context: .      
          push: true
          file: scripts/build/package/Dockerfile
          build-args: |
            GOPROXY=${{ vars.GOPROXY_URL }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
   
