name: Audit, Build, Push
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  audit:
    name: Run linter and tests
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - uses: actions/setup-go@v5
        with:
          cache: false
          go-version: 1.23
          
      - name: Verify deps
        run: go mod verify
        
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1
          
      - name: Run unit tests
        run: go test ./...

  package:
    name: Build and push docker image
    needs: audit
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - uses: docker/setup-buildx-action@v3
      
      - uses: docker/metadata-action@v5
        id: meta
        
      - name: Login to my Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.CONTAINER_REGISTRY_URL }}
          
      - uses: docker/build-push-action@v6
        with:
          context: .      
          push: true
          file: scripts/build/package/Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
   
