name: golangci-lint
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  audit:
    name: lint
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - uses: actions/setup-go@v5
        with:
          go-version: 1.23
          
      - name: Verify deps
        run: go mod verify
        
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1
          
      - name: Run unit tests
        run: go test ./...
      
