name: say-hello
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  what:
    name: Check
    runs-on: self-hosted
    steps:
      - run: ls
      - run: pwd
      - run: uname -a
      - run: ip a
      - run: cat /etc/os-release
      - run: whoami
      - run: echo $HOME
      - run: printenv

