name: say-hello
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  what:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: 1.23
          
      - run: echo $HOME
      
      - run: printenv
      
      - run: ls
      
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - run: ls

