name: say-hello
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  hello:
    name: Say hello
    runs-on: self-hosted
    steps:
      - name: Echo to terminal
        run: |
          echo hello!
      - run: |
          echo hello!!!!

