name: Manual Trigger Action
on:
  workflow_dispatch:

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - run: |
          pwd
          ls
      - uses: actions/checkout@v5
      - run: |
          pwd
          ls
